-- Schema updates for Temtudo Feature Expansion
-- Run these in your Supabase SQL Editor

-- Enhanced Usuarios table
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS data_nascimento DATE;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS estado TEXT;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS longitude NUMERIC;

-- Session tracking for anonymous users
-- Note: id_usuario is optional and not a foreign key due to composite PK on Usuarios
CREATE TABLE IF NOT EXISTS "Sessoes" (
  id_sessao UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  id_usuario BIGINT, -- Optional, no FK constraint due to composite PK on Usuarios
  ip_address TEXT,
  user_agent TEXT
);

-- Disable RLS for Sessoes
ALTER TABLE "Sessoes" DISABLE ROW LEVEL SECURITY;

-- Search/interaction history
CREATE TABLE IF NOT EXISTS "Pesquisas" (
  id_pesquisa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  id_sessao UUID REFERENCES "Sessoes"(id_sessao),
  tipo TEXT, -- 'product_search', 'cart_search', 'market_view', 'cart_optimize'
  dados JSONB -- flexible data storage
);

-- Disable RLS for Pesquisas
ALTER TABLE "Pesquisas" DISABLE ROW LEVEL SECURITY;

-- Cart searches (for analysis)
CREATE TABLE IF NOT EXISTS "Carrinhos" (
  id_carrinho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  id_sessao UUID REFERENCES "Sessoes"(id_sessao),
  produtos JSONB, -- array of product IDs
  mercado_recomendado BIGINT REFERENCES "Mercados"(id_mercado),
  preco_total NUMERIC,
  latitude_usuario NUMERIC,
  longitude_usuario NUMERIC
);

-- Disable RLS for Carrinhos
ALTER TABLE "Carrinhos" DISABLE ROW LEVEL SECURITY;

-- Pending market submissions
CREATE TABLE IF NOT EXISTS "MercadosPendentes" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  nome TEXT NOT NULL,
  endereco TEXT,
  cidade TEXT,
  estado TEXT,
  telefone TEXT,
  email_contato TEXT,
  status TEXT DEFAULT 'pending' -- pending, approved, rejected
);

-- Disable RLS for MercadosPendentes
ALTER TABLE "MercadosPendentes" DISABLE ROW LEVEL SECURITY;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_sessoes_created_at ON "Sessoes"(created_at);
CREATE INDEX IF NOT EXISTS idx_pesquisas_sessao ON "Pesquisas"(id_sessao);
CREATE INDEX IF NOT EXISTS idx_pesquisas_tipo ON "Pesquisas"(tipo);
CREATE INDEX IF NOT EXISTS idx_pesquisas_created_at ON "Pesquisas"(created_at);
CREATE INDEX IF NOT EXISTS idx_carrinhos_sessao ON "Carrinhos"(id_sessao);
CREATE INDEX IF NOT EXISTS idx_carrinhos_mercado ON "Carrinhos"(mercado_recomendado);
